on: 
  workflow_dispatch:
  
name: Test Download Multifile
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out current commit
         
      - name: Set env
        run: |
          echo 'URL<<EOF' >> $GITHUB_ENV
          node ./actionMultifile.js >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        
      - name: use env var directly
        run: echo "$URL"
        
      - run: ls -l 'assets/'
      
      - uses: Angelk90/actions-download-file@master
        id: downloadfile
        name: Download the file
        with:
          url: ${{ env.URL }}
          target: assets/
          filename: '["a.jpg", "b.jpg"]'
          
      - run: ls -l 'assets/'
      
      - name: Check if
        id: verify_diff
        run: |
          git diff assets/ || echo "::set-output name=new_file_exist::true"
          
      - uses: technote-space/get-diff-action@v6
        id: git-diff
        with:
          PATTERNS: +(assets)
          
      - run: echo '${{ env.GIT_DIFF }}' | jq .
        
      - name: Console
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(steps.git-diff.outputs.diff) }}
          
      - name: Commit
        if: steps.git-diff.outputs.diff
        run: |
         git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git config --local user.name "github-actions[bot]"
         git add .
         git commit -m "Add changes" -a
         
      - name: Push
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: ${{ github.ref }}
